import { z } from "zod";
import type {
  ProviderDefinition,
  TriggerDefinition,
  WebhookProcessor,
  WebhookRequest,
  TriggerInfo,
  WebhookMatch,
} from "../base";

// ============================================================================
// Input and State Schemas
// ============================================================================

const OnWebhookInputSchema = z.object({
  path: z.string().optional(),
  method: z.enum(["GET", "POST", "PUT", "DELETE"]).default("POST"),
});

const OnWebhookStateSchema = z.object({
  path: z.string(),
  method: z.string(),
  webhookUrl: z.string(),
});

const OnCronInputSchema = z.object({
  expression: z.string(),
});

const OnCronStateSchema = z.object({
  expression: z.string(),
});

const OnManualInputSchema = z.object({
  name: z.string(),
  description: z.string().optional(),
  input_schema: z.record(z.string(), z.unknown()).optional(),
});

const OnManualStateSchema = z.object({
  name: z.string(),
  description: z.string().optional(),
  input_schema: z.record(z.string(), z.unknown()).optional(),
});

// Type aliases
type OnWebhookInput = z.infer<typeof OnWebhookInputSchema>;
type OnWebhookState = z.infer<typeof OnWebhookStateSchema>;
type OnCronInput = z.infer<typeof OnCronInputSchema>;
type OnCronState = z.infer<typeof OnCronStateSchema>;
type OnManualInput = z.infer<typeof OnManualInputSchema>;
type OnManualState = z.infer<typeof OnManualStateSchema>;

// ============================================================================
// Trigger Definitions
// ============================================================================

const onWebhookTrigger: TriggerDefinition<OnWebhookInput, OnWebhookState> = {
  inputSchema: OnWebhookInputSchema,
  stateSchema: OnWebhookStateSchema,
  lifecycle: {
    async create(ctx) {
      // Builtin webhooks are managed internally by the dashboard
      // The webhook URL is generated by the dashboard and passed here
      const inputPath = ctx.input.path?.replace(/^\//, "") || "";
      return {
        path: inputPath,
        method: ctx.input.method,
        webhookUrl: ctx.webhookUrl,
      };
    },
    async destroy(_ctx) {
      // No external cleanup needed - dashboard handles webhook deletion
    },
    async refresh(ctx) {
      // Builtin webhooks are always valid
      return ctx.state;
    },
  },
};

const onCronTrigger: TriggerDefinition<OnCronInput, OnCronState> = {
  inputSchema: OnCronInputSchema,
  stateSchema: OnCronStateSchema,
  lifecycle: {
    async create(ctx) {
      // Store the cron expression - dashboard handles scheduling
      return {
        expression: ctx.input.expression,
      };
    },
    async destroy(_ctx) {
      // Dashboard handles recurring task cleanup
    },
    async refresh(ctx) {
      // Cron triggers are always valid
      return ctx.state;
    },
  },
};

const onManualTrigger: TriggerDefinition<OnManualInput, OnManualState> = {
  inputSchema: OnManualInputSchema,
  stateSchema: OnManualStateSchema,
  lifecycle: {
    async create(ctx) {
      // Store manual trigger configuration
      return {
        name: ctx.input.name,
        description: ctx.input.description,
        input_schema: ctx.input.input_schema,
      };
    },
    async destroy(_ctx) {
      // No external cleanup needed
    },
    async refresh(ctx) {
      // Manual triggers are always valid
      return ctx.state;
    },
  },
};

// ============================================================================
// Webhook Processor
// ============================================================================

const webhookProcessor: WebhookProcessor = {
  async processWebhook(
    req: WebhookRequest,
    triggers: TriggerInfo[],
    _secrets: Record<string, string>
  ): Promise<WebhookMatch[]> {
    // For builtin webhooks, all triggers associated with this webhook should fire
    // The dashboard routes webhooks to specific triggers based on path
    return triggers.map((trigger) => ({
      triggerId: trigger.id,
      event: {
        body: req.body,
        headers: req.headers,
        method: req.method,
        path: req.path,
      },
    }));
  },
};

// ============================================================================
// Provider Definition
// ============================================================================

export const BuiltinServerProvider: ProviderDefinition = {
  providerType: "builtin",
  setupSteps: [], // No setup required for builtin provider
  webhookProcessor,
  triggerDefinitions: {
    onWebhook: onWebhookTrigger,
    onCron: onCronTrigger,
    onManual: onManualTrigger,
  },
};
