version: '3.8'

services:
  # Main web application
  app:
    image: ${REGISTRY:-ghcr.io}/floww/dashboard:${VERSION:-latest}
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
        failure_action: rollback
      rollback_config:
        parallelism: 1
        delay: 10s
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.25'
          memory: 256M
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.floww-dashboard.rule=Host(`${DOMAIN:-dashboard.floww.io}`)"
        - "traefik.http.routers.floww-dashboard.entrypoints=websecure"
        - "traefik.http.routers.floww-dashboard.tls.certresolver=letsencrypt"
        - "traefik.http.services.floww-dashboard.loadbalancer.server.port=3000"
        - "traefik.http.services.floww-dashboard.loadbalancer.healthcheck.path=/health"
        - "traefik.http.services.floww-dashboard.loadbalancer.healthcheck.interval=30s"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - AUTH_TYPE=${AUTH_TYPE:-workos}
      - AUTH_CLIENT_ID=${AUTH_CLIENT_ID}
      - AUTH_CLIENT_SECRET=${AUTH_CLIENT_SECRET}
      - WORKOS_API_KEY=${WORKOS_API_KEY}
      - WORKOS_CLIENT_ID=${WORKOS_CLIENT_ID}
      - JWT_SECRET=${JWT_SECRET}
      - SESSION_SECRET=${SESSION_SECRET}
      - CENTRIFUGO_URL=${CENTRIFUGO_URL:-http://centrifugo:8000}
      - CENTRIFUGO_API_KEY=${CENTRIFUGO_API_KEY}
      - CENTRIFUGO_SECRET=${CENTRIFUGO_SECRET}
      - IS_CLOUD=${IS_CLOUD:-false}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
      - SENTRY_DSN=${SENTRY_DSN}
    networks:
      - floww-network
      - traefik-public
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # Background job worker
  worker:
    image: ${REGISTRY:-ghcr.io}/floww/dashboard:${VERSION:-latest}
    command: ["node", "dist/server/jobs/worker.js"]
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.1'
          memory: 128M
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - WORKER_CONCURRENCY=${WORKER_CONCURRENCY:-5}
      - SENTRY_DSN=${SENTRY_DSN}
    networks:
      - floww-network

  # Centrifugo WebSocket server
  centrifugo:
    image: centrifugo/centrifugo:v5
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.floww-centrifugo.rule=Host(`${CENTRIFUGO_DOMAIN:-ws.floww.io}`)"
        - "traefik.http.routers.floww-centrifugo.entrypoints=websecure"
        - "traefik.http.routers.floww-centrifugo.tls.certresolver=letsencrypt"
        - "traefik.http.services.floww-centrifugo.loadbalancer.server.port=8000"
    environment:
      CENTRIFUGO_API_KEY: ${CENTRIFUGO_API_KEY}
      CENTRIFUGO_TOKEN_HMAC_SECRET_KEY: ${CENTRIFUGO_SECRET}
      CENTRIFUGO_ADMIN_ENABLED: "false"
    command: centrifugo --config=/etc/centrifugo/config.json
    configs:
      - source: centrifugo_config
        target: /etc/centrifugo/config.json
    networks:
      - floww-network
      - traefik-public

configs:
  centrifugo_config:
    file: ./centrifugo/config.json

networks:
  floww-network:
    driver: overlay
    attachable: true
  traefik-public:
    external: true
