version: "3.8"

services:
  floww-dashboard:
    image: "ghcr.io/usefloww/floww-dashboard:latest"

    networks:
      - traefik-staging-net

    environment:
      - NODE_ENV=staging
      - PORT=8080
      - HOST=0.0.0.0
      - BACKEND_API_URL="http://floww-backend-staging_app:8000"

    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        order: start-first
      rollback_config:
        parallelism: 1
        order: stop-first
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.floww-dashboard-staging.rule=Host(`dashboard.flow.toondn.app`)"
        - "traefik.http.routers.floww-dashboard-staging.entrypoints=websecure"
        - "traefik.http.routers.floww-dashboard-staging.tls.certresolver=myresolver"
        - "traefik.http.services.floww-dashboard-staging.loadbalancer.server.port=8080"

    # healthcheck:
    #   test: ["CMD", "wget", "--spider", "-q", "http://localhost:8080/"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 20s

networks:
  traefik-staging-net:
    external: true
