/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UpgradeRouteImport } from './routes/upgrade'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as ProvidersRouteImport } from './routes/providers'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkflowsIndexRouteImport } from './routes/workflows/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as ProfileIndexRouteImport } from './routes/profile/index'
import { Route as WorkflowsWorkflowIdDeploymentsRouteImport } from './routes/workflows/$workflowId.deployments'
import { Route as WorkflowsWorkflowIdExecutionsExecutionIdRouteImport } from './routes/workflows/$workflowId.executions.$executionId'
import { Route as WorkflowsWorkflowIdDeploymentsDeploymentIdEditRouteImport } from './routes/workflows/$workflowId.deployments.$deploymentId.edit'

const UpgradeRoute = UpgradeRouteImport.update({
  id: '/upgrade',
  path: '/upgrade',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvidersRoute = ProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsIndexRoute = WorkflowsIndexRouteImport.update({
  id: '/workflows/',
  path: '/workflows/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsWorkflowIdDeploymentsRoute =
  WorkflowsWorkflowIdDeploymentsRouteImport.update({
    id: '/workflows/$workflowId/deployments',
    path: '/workflows/$workflowId/deployments',
    getParentRoute: () => rootRouteImport,
  } as any)
const WorkflowsWorkflowIdExecutionsExecutionIdRoute =
  WorkflowsWorkflowIdExecutionsExecutionIdRouteImport.update({
    id: '/workflows/$workflowId/executions/$executionId',
    path: '/workflows/$workflowId/executions/$executionId',
    getParentRoute: () => rootRouteImport,
  } as any)
const WorkflowsWorkflowIdDeploymentsDeploymentIdEditRoute =
  WorkflowsWorkflowIdDeploymentsDeploymentIdEditRouteImport.update({
    id: '/$deploymentId/edit',
    path: '/$deploymentId/edit',
    getParentRoute: () => WorkflowsWorkflowIdDeploymentsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/providers': typeof ProvidersRoute
  '/setup': typeof SetupRoute
  '/upgrade': typeof UpgradeRoute
  '/profile': typeof ProfileIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/workflows': typeof WorkflowsIndexRoute
  '/workflows/$workflowId/deployments': typeof WorkflowsWorkflowIdDeploymentsRouteWithChildren
  '/workflows/$workflowId/executions/$executionId': typeof WorkflowsWorkflowIdExecutionsExecutionIdRoute
  '/workflows/$workflowId/deployments/$deploymentId/edit': typeof WorkflowsWorkflowIdDeploymentsDeploymentIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/providers': typeof ProvidersRoute
  '/setup': typeof SetupRoute
  '/upgrade': typeof UpgradeRoute
  '/profile': typeof ProfileIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/workflows': typeof WorkflowsIndexRoute
  '/workflows/$workflowId/deployments': typeof WorkflowsWorkflowIdDeploymentsRouteWithChildren
  '/workflows/$workflowId/executions/$executionId': typeof WorkflowsWorkflowIdExecutionsExecutionIdRoute
  '/workflows/$workflowId/deployments/$deploymentId/edit': typeof WorkflowsWorkflowIdDeploymentsDeploymentIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/providers': typeof ProvidersRoute
  '/setup': typeof SetupRoute
  '/upgrade': typeof UpgradeRoute
  '/profile/': typeof ProfileIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/workflows/': typeof WorkflowsIndexRoute
  '/workflows/$workflowId/deployments': typeof WorkflowsWorkflowIdDeploymentsRouteWithChildren
  '/workflows/$workflowId/executions/$executionId': typeof WorkflowsWorkflowIdExecutionsExecutionIdRoute
  '/workflows/$workflowId/deployments/$deploymentId/edit': typeof WorkflowsWorkflowIdDeploymentsDeploymentIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/checkout'
    | '/login'
    | '/providers'
    | '/setup'
    | '/upgrade'
    | '/profile'
    | '/settings'
    | '/workflows'
    | '/workflows/$workflowId/deployments'
    | '/workflows/$workflowId/executions/$executionId'
    | '/workflows/$workflowId/deployments/$deploymentId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checkout'
    | '/login'
    | '/providers'
    | '/setup'
    | '/upgrade'
    | '/profile'
    | '/settings'
    | '/workflows'
    | '/workflows/$workflowId/deployments'
    | '/workflows/$workflowId/executions/$executionId'
    | '/workflows/$workflowId/deployments/$deploymentId/edit'
  id:
    | '__root__'
    | '/'
    | '/checkout'
    | '/login'
    | '/providers'
    | '/setup'
    | '/upgrade'
    | '/profile/'
    | '/settings/'
    | '/workflows/'
    | '/workflows/$workflowId/deployments'
    | '/workflows/$workflowId/executions/$executionId'
    | '/workflows/$workflowId/deployments/$deploymentId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CheckoutRoute: typeof CheckoutRoute
  LoginRoute: typeof LoginRoute
  ProvidersRoute: typeof ProvidersRoute
  SetupRoute: typeof SetupRoute
  UpgradeRoute: typeof UpgradeRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  WorkflowsIndexRoute: typeof WorkflowsIndexRoute
  WorkflowsWorkflowIdDeploymentsRoute: typeof WorkflowsWorkflowIdDeploymentsRouteWithChildren
  WorkflowsWorkflowIdExecutionsExecutionIdRoute: typeof WorkflowsWorkflowIdExecutionsExecutionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upgrade': {
      id: '/upgrade'
      path: '/upgrade'
      fullPath: '/upgrade'
      preLoaderRoute: typeof UpgradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/providers': {
      id: '/providers'
      path: '/providers'
      fullPath: '/providers'
      preLoaderRoute: typeof ProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/': {
      id: '/workflows/'
      path: '/workflows'
      fullPath: '/workflows'
      preLoaderRoute: typeof WorkflowsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/$workflowId/deployments': {
      id: '/workflows/$workflowId/deployments'
      path: '/workflows/$workflowId/deployments'
      fullPath: '/workflows/$workflowId/deployments'
      preLoaderRoute: typeof WorkflowsWorkflowIdDeploymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/$workflowId/executions/$executionId': {
      id: '/workflows/$workflowId/executions/$executionId'
      path: '/workflows/$workflowId/executions/$executionId'
      fullPath: '/workflows/$workflowId/executions/$executionId'
      preLoaderRoute: typeof WorkflowsWorkflowIdExecutionsExecutionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/$workflowId/deployments/$deploymentId/edit': {
      id: '/workflows/$workflowId/deployments/$deploymentId/edit'
      path: '/$deploymentId/edit'
      fullPath: '/workflows/$workflowId/deployments/$deploymentId/edit'
      preLoaderRoute: typeof WorkflowsWorkflowIdDeploymentsDeploymentIdEditRouteImport
      parentRoute: typeof WorkflowsWorkflowIdDeploymentsRoute
    }
  }
}

interface WorkflowsWorkflowIdDeploymentsRouteChildren {
  WorkflowsWorkflowIdDeploymentsDeploymentIdEditRoute: typeof WorkflowsWorkflowIdDeploymentsDeploymentIdEditRoute
}

const WorkflowsWorkflowIdDeploymentsRouteChildren: WorkflowsWorkflowIdDeploymentsRouteChildren =
  {
    WorkflowsWorkflowIdDeploymentsDeploymentIdEditRoute:
      WorkflowsWorkflowIdDeploymentsDeploymentIdEditRoute,
  }

const WorkflowsWorkflowIdDeploymentsRouteWithChildren =
  WorkflowsWorkflowIdDeploymentsRoute._addFileChildren(
    WorkflowsWorkflowIdDeploymentsRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CheckoutRoute: CheckoutRoute,
  LoginRoute: LoginRoute,
  ProvidersRoute: ProvidersRoute,
  SetupRoute: SetupRoute,
  UpgradeRoute: UpgradeRoute,
  ProfileIndexRoute: ProfileIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  WorkflowsIndexRoute: WorkflowsIndexRoute,
  WorkflowsWorkflowIdDeploymentsRoute:
    WorkflowsWorkflowIdDeploymentsRouteWithChildren,
  WorkflowsWorkflowIdExecutionsExecutionIdRoute:
    WorkflowsWorkflowIdExecutionsExecutionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
